version: '3.8'

services:
  backend:
    build: ./backend
    command: flask run -h 0.0.0.0
    volumes:
      - ./backend:/usr/src/app/
    ports:
      - 5000:5000
    env_file:
      - ./backend/.env
    depends_on:
      - db
  
  db:
    image: postgres:13-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=b_user
      - POSTGRES_PASSWORD=9ELj9x9f88aMSW3b
      - POSTGRES_DB=birthday_reminder_db

volumes:
  postgres_data: